[Debug] [vite] connecting... (client, line 495)
[Debug] [vite] connected. (client, line 618)
[Error] ReferenceError: Can't find variable: Orders
	Router (App.tsx:475:156)
	renderWithHooks (chunk-RPCDYKBN.js:11548)
	updateFunctionComponent (chunk-RPCDYKBN.js:14582)
	callCallback2 (chunk-RPCDYKBN.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-RPCDYKBN.js:3699)
	invokeGuardedCallback (chunk-RPCDYKBN.js:3733)
	beginWork$1 (chunk-RPCDYKBN.js:19765)
	performUnitOfWork (chunk-RPCDYKBN.js:19198)
	workLoopSync (chunk-RPCDYKBN.js:19137)
	renderRootSync (chunk-RPCDYKBN.js:19116)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18874)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] ReferenceError: Can't find variable: Orders
	Router (App.tsx:475:156)
	renderWithHooks (chunk-RPCDYKBN.js:11548)
	updateFunctionComponent (chunk-RPCDYKBN.js:14582)
	callCallback2 (chunk-RPCDYKBN.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-RPCDYKBN.js:3699)
	invokeGuardedCallback (chunk-RPCDYKBN.js:3733)
	beginWork$1 (chunk-RPCDYKBN.js:19765)
	performUnitOfWork (chunk-RPCDYKBN.js:19198)
	workLoopSync (chunk-RPCDYKBN.js:19137)
	renderRootSync (chunk-RPCDYKBN.js:19116)
	recoverFromConcurrentError (chunk-RPCDYKBN.js:18736)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18879)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] The above error occurred in the <Router> component:

Router@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/src/App.tsx:86:49
TooltipProviderProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/chunk-OXZDJRWN.js:38:52
TooltipProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@radix-ui_react-tooltip.js:67:12
QueryClientProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js:2805:9
App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
	logCapturedError (chunk-RPCDYKBN.js:14032)
	(anonymous function) (chunk-RPCDYKBN.js:14052)
	callCallback (chunk-RPCDYKBN.js:11248)
	commitUpdateQueue (chunk-RPCDYKBN.js:11265)
	commitLayoutEffectOnFiber (chunk-RPCDYKBN.js:17093)
	commitLayoutMountEffects_complete (chunk-RPCDYKBN.js:17980)
	commitLayoutEffects_begin (chunk-RPCDYKBN.js:17969)
	commitLayoutEffects (chunk-RPCDYKBN.js:17920)
	commitRootImpl (chunk-RPCDYKBN.js:19353)
	commitRoot (chunk-RPCDYKBN.js:19277)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18895)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] ReferenceError: Can't find variable: Orders
	flushSyncCallbacks (chunk-RPCDYKBN.js:9129)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Debug] [vite] connecting... (client, line 495)
[Debug] [vite] connected. (client, line 618)
[Error] ReferenceError: Can't find variable: Orders
	Router (App.tsx:475:156)
	renderWithHooks (chunk-RPCDYKBN.js:11548)
	updateFunctionComponent (chunk-RPCDYKBN.js:14582)
	callCallback2 (chunk-RPCDYKBN.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-RPCDYKBN.js:3699)
	invokeGuardedCallback (chunk-RPCDYKBN.js:3733)
	beginWork$1 (chunk-RPCDYKBN.js:19765)
	performUnitOfWork (chunk-RPCDYKBN.js:19198)
	workLoopSync (chunk-RPCDYKBN.js:19137)
	renderRootSync (chunk-RPCDYKBN.js:19116)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18874)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] ReferenceError: Can't find variable: Orders
	Router (App.tsx:475:156)
	renderWithHooks (chunk-RPCDYKBN.js:11548)
	updateFunctionComponent (chunk-RPCDYKBN.js:14582)
	callCallback2 (chunk-RPCDYKBN.js:3674)
	dispatchEvent
	invokeGuardedCallbackDev (chunk-RPCDYKBN.js:3699)
	invokeGuardedCallback (chunk-RPCDYKBN.js:3733)
	beginWork$1 (chunk-RPCDYKBN.js:19765)
	performUnitOfWork (chunk-RPCDYKBN.js:19198)
	workLoopSync (chunk-RPCDYKBN.js:19137)
	renderRootSync (chunk-RPCDYKBN.js:19116)
	recoverFromConcurrentError (chunk-RPCDYKBN.js:18736)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18879)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] The above error occurred in the <Router> component:

Router@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/src/App.tsx:86:49
TooltipProviderProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/chunk-OXZDJRWN.js:38:52
TooltipProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@radix-ui_react-tooltip.js:67:12
QueryClientProvider@https://3c2c7a34-437b-4cc6-bd2a-ac2fbc7eb5cd-00-2i9xniom6qmuw.picard.replit.dev/@fs/home/runner/workspace/node_modules/.vite/deps/@tanstack_react-query.js:2805:9
App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
	logCapturedError (chunk-RPCDYKBN.js:14032)
	(anonymous function) (chunk-RPCDYKBN.js:14052)
	callCallback (chunk-RPCDYKBN.js:11248)
	commitUpdateQueue (chunk-RPCDYKBN.js:11265)
	commitLayoutEffectOnFiber (chunk-RPCDYKBN.js:17093)
	commitLayoutMountEffects_complete (chunk-RPCDYKBN.js:17980)
	commitLayoutEffects_begin (chunk-RPCDYKBN.js:17969)
	commitLayoutEffects (chunk-RPCDYKBN.js:17920)
	commitRootImpl (chunk-RPCDYKBN.js:19353)
	commitRoot (chunk-RPCDYKBN.js:19277)
	performSyncWorkOnRoot (chunk-RPCDYKBN.js:18895)
	flushSyncCallbacks (chunk-RPCDYKBN.js:9119)
	(anonymous function) (chunk-RPCDYKBN.js:18627)
[Error] ReferenceError: Can't find variable: Orders
	flushSyncCallbacks (chunk-RPCDYKBN.js:9129)
	(anonymous function) (chunk-RPCDYKBN.js:18627)